name: bamboo_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  file_picker: ^8.1.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.2.1
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  geolocator: ^13.0.2
  go_router: ^14.2.7
  google_maps_flutter: ^2.9.0
  permission_handler: ^11.3.1
  supabase_flutter: ^2.8.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/.env
    - assets/images/
    - assets/dark_mode_map.json
