// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdtHLZcgbC0EJK8si_TnPiKwkUc0jyqSI',
    appId: '1:93202021060:web:60d225159ea420a60aa791',
    messagingSenderId: '93202021060',
    projectId: 'bambookkn-2a364',
    authDomain: 'bambookkn-2a364.firebaseapp.com',
    storageBucket: 'bambookkn-2a364.appspot.com',
    measurementId: 'G-096D77CCK6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAY8qjRRcZtc-Y6QRgil9mFvgTWW6usJvc',
    appId: '1:93202021060:android:f28591efb778b87a0aa791',
    messagingSenderId: '93202021060',
    projectId: 'bambookkn-2a364',
    storageBucket: 'bambookkn-2a364.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ8t0MQzTfL67gCoWlav5-1_rEeXSXKlE',
    appId: '1:93202021060:ios:a8f559a2c2aa39a80aa791',
    messagingSenderId: '93202021060',
    projectId: 'bambookkn-2a364',
    storageBucket: 'bambookkn-2a364.appspot.com',
    iosBundleId: 'com.example.bambooApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ8t0MQzTfL67gCoWlav5-1_rEeXSXKlE',
    appId: '1:93202021060:ios:a8f559a2c2aa39a80aa791',
    messagingSenderId: '93202021060',
    projectId: 'bambookkn-2a364',
    storageBucket: 'bambookkn-2a364.appspot.com',
    iosBundleId: 'com.example.bambooApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdtHLZcgbC0EJK8si_TnPiKwkUc0jyqSI',
    appId: '1:93202021060:web:54707ca0414830ba0aa791',
    messagingSenderId: '93202021060',
    projectId: 'bambookkn-2a364',
    authDomain: 'bambookkn-2a364.firebaseapp.com',
    storageBucket: 'bambookkn-2a364.appspot.com',
    measurementId: 'G-JDKWRDPQJW',
  );

}